name: Production build
on:
  push:
    branches: [main]
jobs:
  build_ios:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production
  build_android:
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production
